version: '3.8'

services:
    web:
        build: .
        image: ghcr.io/pongchanan/django-polls
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        environment:
            - DEBUG=1
            - DJANGO_SETTINGS_MODULE=mysite.settings
        depends_on:
            - db
        command: python manage.py runserver 0.0.0.0:8000

    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=django_db
            - POSTGRES_USER=django_user
            - POSTGRES_PASSWORD=django_password

volumes:
    postgres_data:
