name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    packages: write

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Build Docker image locally
              run: |
                  docker build -t ghcr.io/pongchanan/django-polls:latest .

            - name: Run Tests
              run: |
                  docker compose -f docker-compose.yml up -d
                  # Wait for PostgreSQL to be ready
                  echo "Waiting for PostgreSQL to be ready..."
                  timeout 15s bash -c 'until docker compose -f docker-compose.yml exec -T db pg_isready -U your_actual_db_user; do sleep 1; done'
                  # Run the tests
                  docker compose -f docker-compose.yml exec -T web python manage.py test

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PAT }}

            - name: Push Docker image
              run: docker push ghcr.io/pongchanan/django-polls:latest

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      cd ~/django-test
                      docker compose -f docker-compose.prod.yml down
                      docker image rm ghcr.io/pongchanan/django-polls:latest || true
                      docker compose -f docker-compose.prod.yml pull
                      docker compose -f docker-compose.prod.yml up -d
