name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    packages: write

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Tests
              run: |
                  docker compose -f docker-compose.yml up -d
                  docker compose -f docker-compose.yml exec -T web python manage.py test
                  docker image rm ghcr.io/pongchanan/django-polls:latest

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ghcr.io/pongchanan/django-polls:latest

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      cd ~/django-test
                      docker compose -f docker-compose.prod.yml down
                      docker image rm ghcr.io/pongchanan/django-polls:latest
                      docker compose -f docker-compose.prod.yml pull
                      docker compose -f docker-compose.prod.yml up -d
